/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author informatica_prac
 */
public class RegistroSalida extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reserva_Sala
     */
    public RegistroSalida() {
    
        
        initComponents();
         //Check apagado residente
        cbSeleccionarRut.setEnabled(false);
        //Check apagado uso estacionamiento
        cbSeleccionarPatente.setEnabled(false);
        //import java.util.Calendar;
        Calendar cal=Calendar.getInstance();
        
        String fecha=cal.get(Calendar.DATE)+"/"+cal.get(cal.MONTH)+"/"+cal.get(cal.YEAR);
        String hora=cal.get(cal.HOUR_OF_DAY)+ ":"+cal.get(cal.MINUTE)+":"+cal.get(cal.SECOND);
        String fechahora=fecha +" : "+hora;
       
        //fecha y hora sistema
       // JOptionPane.showMessageDialog(null, fechahora);
        this.LbFechaHora.setText(fechahora);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbSeleccionarRut = new javax.swing.JComboBox<>();
        btnGuardarSalida = new javax.swing.JButton();
        chSalidaRut = new javax.swing.JCheckBox();
        chSalidaVehiculo = new javax.swing.JCheckBox();
        cbSeleccionarPatente = new javax.swing.JComboBox<>();
        btnCerrar = new javax.swing.JButton();
        LbFechaHora = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("REGISTRAR SALIDA");

        cbSeleccionarRut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Rut", "101", "102", "103", "104", "201", "202", "203", "204", "301", "302", "303", "304" }));
        cbSeleccionarRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSeleccionarRutActionPerformed(evt);
            }
        });

        btnGuardarSalida.setText("GUARDAR SALIDA");
        btnGuardarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSalidaActionPerformed(evt);
            }
        });

        chSalidaRut.setText("Salida Rut");
        chSalidaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chSalidaRutActionPerformed(evt);
            }
        });

        chSalidaVehiculo.setText("Salida vehiculo");
        chSalidaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chSalidaVehiculoActionPerformed(evt);
            }
        });

        cbSeleccionarPatente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Patente", "1", "2", "3", "4", "5" }));
        cbSeleccionarPatente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSeleccionarPatenteActionPerformed(evt);
            }
        });

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        LbFechaHora.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LbFechaHoraAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        LbFechaHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbFechaHoraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnGuardarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chSalidaRut)
                            .addComponent(chSalidaVehiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSeleccionarRut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSeleccionarPatente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(249, 249, 249))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSeleccionarRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chSalidaRut))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSeleccionarPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chSalidaVehiculo))
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LbFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSeleccionarRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSeleccionarRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSeleccionarRutActionPerformed

    private void cbSeleccionarPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSeleccionarPatenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSeleccionarPatenteActionPerformed

    private void chSalidaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chSalidaRutActionPerformed
        // TODO add your handling code here:
         if(chSalidaRut.isSelected()){
            cbSeleccionarRut.setEnabled(true);
        }else{
            cbSeleccionarRut.setEnabled(false);
        }
    }//GEN-LAST:event_chSalidaRutActionPerformed

    private void LbFechaHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbFechaHoraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LbFechaHoraMouseClicked

    private void LbFechaHoraAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LbFechaHoraAncestorAdded
        // TODO add your handling code here:
       
    }//GEN-LAST:event_LbFechaHoraAncestorAdded

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
       
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void chSalidaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chSalidaVehiculoActionPerformed
        // TODO add your handling code here:
         if(chSalidaVehiculo.isSelected()){
            cbSeleccionarPatente.setEnabled(true);
        }else{
            cbSeleccionarPatente.setEnabled(false);
        }
    }//GEN-LAST:event_chSalidaVehiculoActionPerformed

    private void btnGuardarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSalidaActionPerformed
        // TODO add your handling code here:
        String selectrut = (String)cbSeleccionarRut.getSelectedItem();
        String selectpatente = (String)cbSeleccionarPatente.getSelectedItem();
       
        boolean salidavehiculo = chSalidaVehiculo.isSelected();
        
        if(selectrut.isEmpty() || selectpatente.isEmpty() || salidavehiculo == false){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
        }else{
            JOptionPane.showMessageDialog(this, "Salida registrada correctamente");
        }
        
        
        
    }//GEN-LAST:event_btnGuardarSalidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbFechaHora;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardarSalida;
    private javax.swing.JComboBox<String> cbSeleccionarPatente;
    private javax.swing.JComboBox<String> cbSeleccionarRut;
    private javax.swing.JCheckBox chSalidaRut;
    private javax.swing.JCheckBox chSalidaVehiculo;
    // End of variables declaration//GEN-END:variables
}
