/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.Calendar;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author informatica_prac
 */
public class RegistroSalida_respaldo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reserva_Sala
     */
    public RegistroSalida_respaldo() {
    
        
        initComponents();
        // Bloquear redimension
        this.setResizable(false);
        // Boton cerrar y ocultar JInternalFrame
        this.setDefaultCloseOperation(JInternalFrame.HIDE_ON_CLOSE);
         //Check apagado residente
        cbSeleccionarRut.setEnabled(false);
        //Check apagado uso estacionamiento
        cbSeleccionarPatente.setEnabled(false);
        //import java.util.Calendar;
        Calendar cal=Calendar.getInstance();
        
        String fecha=cal.get(Calendar.DATE)+"/"+cal.get(cal.MONTH)+"/"+cal.get(cal.YEAR);
        String hora=cal.get(cal.HOUR_OF_DAY)+ ":"+cal.get(cal.MINUTE)+":"+cal.get(cal.SECOND);
        String fechahora=fecha +" : "+hora;
       
        //fecha y hora sistema
       // JOptionPane.showMessageDialog(null, fechahora);
        this.LbFechaHora.setText(fechahora);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        chSalidaRut = new javax.swing.JCheckBox();
        cbSeleccionarRut = new javax.swing.JComboBox<>();
        chSalidaVehiculo = new javax.swing.JCheckBox();
        cbSeleccionarPatente = new javax.swing.JComboBox<>();
        btnCerrar = new javax.swing.JButton();
        btnGuardarSalida = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LbFechaHora = new javax.swing.JLabel();

        setResizable(true);
        setTitle("REGISTRAR SALIDA");

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chSalidaRut.setBackground(new java.awt.Color(0, 51, 102));
        chSalidaRut.setForeground(new java.awt.Color(255, 255, 255));
        chSalidaRut.setText("SALIDA POR RUT:");
        chSalidaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chSalidaRutActionPerformed(evt);
            }
        });
        jPanel2.add(chSalidaRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        cbSeleccionarRut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Rut", "101", "102", "103", "104", "201", "202", "203", "204", "301", "302", "303", "304" }));
        cbSeleccionarRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSeleccionarRutActionPerformed(evt);
            }
        });
        jPanel2.add(cbSeleccionarRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 238, -1));

        chSalidaVehiculo.setBackground(new java.awt.Color(0, 51, 102));
        chSalidaVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        chSalidaVehiculo.setText("SALIDA DE VEHICULO: ");
        chSalidaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chSalidaVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(chSalidaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        cbSeleccionarPatente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Patente", "1", "2", "3", "4", "5" }));
        cbSeleccionarPatente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSeleccionarPatenteActionPerformed(evt);
            }
        });
        jPanel2.add(cbSeleccionarPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 238, -1));

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 158, 55));

        btnGuardarSalida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardarSalida.setText("GUARDAR SALIDA");
        btnGuardarSalida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSalidaActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 158, 55));

        jPanel3.setBackground(new java.awt.Color(204, 153, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("SALIDA DE VISITAS Y VEHICULOS");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("FECHA Y HORA:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        LbFechaHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(LbFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 240, 22));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSeleccionarRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSeleccionarRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSeleccionarRutActionPerformed

    private void cbSeleccionarPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSeleccionarPatenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSeleccionarPatenteActionPerformed

    private void chSalidaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chSalidaRutActionPerformed
        // TODO add your handling code here:
         if(chSalidaRut.isSelected()){
            cbSeleccionarRut.setEnabled(true);
        }else{
            cbSeleccionarRut.setEnabled(false);
        }
    }//GEN-LAST:event_chSalidaRutActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
       
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void chSalidaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chSalidaVehiculoActionPerformed
        // TODO add your handling code here:
         if(chSalidaVehiculo.isSelected()){
            cbSeleccionarPatente.setEnabled(true);
        }else{
            cbSeleccionarPatente.setEnabled(false);
        }
    }//GEN-LAST:event_chSalidaVehiculoActionPerformed

    private void btnGuardarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSalidaActionPerformed
        // TODO add your handling code here:
        String selectrut = (String)cbSeleccionarRut.getSelectedItem();
        String selectpatente = (String)cbSeleccionarPatente.getSelectedItem();
       
        boolean salidavehiculo = chSalidaVehiculo.isSelected();
        
        if(selectrut.isEmpty() || selectpatente.isEmpty() || salidavehiculo == false){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
        }else{
            JOptionPane.showMessageDialog(this, "Salida registrada correctamente");
        }
        
        
        
    }//GEN-LAST:event_btnGuardarSalidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbFechaHora;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardarSalida;
    private javax.swing.JComboBox<String> cbSeleccionarPatente;
    private javax.swing.JComboBox<String> cbSeleccionarRut;
    private javax.swing.JCheckBox chSalidaRut;
    private javax.swing.JCheckBox chSalidaVehiculo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
